apiVersion: v1
kind: PersistentVolume
metadata:
  name: docker-pv
  namespace: jenkins
spec:
  storageClassName: manual
  capacity:
    storage: 300M
  accessModes:
    - ReadWriteOnce
  local:
    path: "//var/run/"
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - kind-worker
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: docker-pvc
  namespace: jenkins
spec:
  resources:
    requests:
      storage: 300M
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  volumeName: docker-pv  