apiVersion: v1
kind: PersistentVolume
metadata:
  name: jenkins-pv
  namespace: jenkins
spec:
  storageClassName: manual
  capacity:
    storage: 300M
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/jenkins"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jenkins-pvc
  namespace: jenkins
spec:
  resources:
    requests:
      storage: 300M
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  volumeName: jenkins-pv  