apiVersion: v1
kind: PersistentVolume
metadata:
  name: nexus-pv
  namespace: devops-tools  
spec:
  storageClassName: manual
  capacity:
    storage: 300M
  accessModes:
    - ReadWriteOnce
  local:
    path: "/nexus"
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - kind-worker    
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nexus-pvc
  namespace: devops-tools
spec:
  resources:
    requests:
      storage: 300M
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  volumeName: nexus-pv  