---
apiVersion: v1
kind: Pod
metadata:
  labels:
    run: test
  name: test
  namespace: test-app
spec:
  containers:
  - image: k8s.gcr.io/echoserver:1.4
    name: test
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
